site_name: Student Resources
theme: 
 name: readthedocs
 locale: fr
 user_color_mode_toggle: true
nav:
  - Home: index.md
  - Files:
      - "Math Notes": math-notes.pdf
      - "History Outline": history-outline.pdf
  - Speciality physics:
      - "bomboclat": bomboclat.pdf